language: node_js
node_js:
  - '12'
cacne:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
stages:
  - test
jobs:
  include:
    # - stage: compile
    #   name: 'tsc build'
    #   script: 'yarn build'

    # - name: 'tslint'
    #   script: 'yarn lint'

    - stage: test
      name: 'Jest tests'
      before_script: yarn lint && yarn build
      script: 'yarn test'
      after_success: bash <(curl -s https://codecov.io/bash)
