language: node_js
cache: yarn
node_js:
  - '10'
  - '8'  
before_script:
  - npm --v
script: 
  # Insall yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm run bootstrap
  - npm run build
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
