language: node_js
node_js:
  - '12'
cacne:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: 'Lint & Build'
      name: 'Typescript build'
      script: 'yarn build'

      name: 'tslint'
      script: 'yarn lint'
    
    - stage: 'Tests'
      name: 'Jest tests'
      script: 'yarn test'
      after_success: bash <(curl -s https://codecov.io/bash)