module.exports = {
  roots: [
    '<rootDir>/packages/auth-google',
    '<rootDir>/packages/core',
    '<rootDir>/packages/filesystem-store',
    '<rootDir>/packages/rest',
    '<rootDir>/packages/rest-client-fetch',
    '<rootDir>/packages/rest-service',
    '<rootDir>/packages/inject',
    '<rootDir>/packages/logging',
    '<rootDir>/packages/mongodb-store',
    '<rootDir>/packages/redis-store',
    '<rootDir>/packages/repository',
    '<rootDir>/packages/utils',
    '<rootDir>/packages/websocket-api',
    '<rootDir>/packages/shades',
    '<rootDir>/packages/shades-common-components',
    '<rootDir>/packages/shades-lottie',
    '<rootDir>/packages/shades-nipple',
  ],
  testEnvironment: 'node',
  moduleFileExtensions: ['js', 'json', 'node'],
  collectCoverage: true,
  collectCoverageFrom: ['**/*.{js,jsx}', '!**/node_modules/**'],
  coverageReporters: ['text', 'json', 'html', 'cobertura'],
  reporters: ['default', 'jest-junit'],
}
