name: Lint

on: [push]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the docker-compose stack
        run: docker-compose up -d     
      - name: Install dependencies
        run: docker-compose exec -T app yarn install
      - name: Lint
        run: docker-compose exec -T app yarn lint
        env:
          CI: true
