name: Lint

on: [push]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
        env:
          CI: true
