name: Build, lint and jest tests

on: [push]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the docker-compose stack
        run: docker-compose up -d     
      - name: Install dependencies
        run: docker exec furystackfurystack_app_1 yarn install
      - name: Lint
        run: docker exec furystackfurystack_app_1 yarn lint
      - name: Build
        run: docker exec furystackfurystack_app_1 yarn build
      - name: Test
        run: docker exec furystackfurystack_app_1 yarn test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

        env:
          CI: true
