name: UI tests for Showcase app
on: [push]
jobs:
  build:
    name: Build and run UI tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x, 24.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build Showcase app
        run: yarn build:showcase
      - name: Install Playwright browsers
        run: yarn workspace @furystack/shades-showcase-app e2e install --with-deps
      - name: Execute tests
        run: yarn workspace @furystack/shades-showcase-app e2e test
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: packages/shades-showcase-app/test-results
          name: Download-screenshots
