name: UI tests for Showcase app
on: [push]
jobs:
  build:
    name: Build and run UI tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Create Bundle
        run: yarn workspace @furystack/shades-showcase-app build
      - name: Serve Bundle
        run: sudo apt install lighttpd -y && lighttpd -f lighttpd.conf && curl http://localhost:8080
        working-directory: packages/shades-showcase-app
      - name: Install Playwright browsers
        run: yarn workspace @furystack/shades-showcase-app e2e install --with-deps
      - name: execute tests
        run: yarn workspace @furystack/shades-showcase-app e2e test
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: packages/shades-showcase-app/test-results
          name: Download-screenshots  