name: UI tests for Showcase app
on: [push]
jobs:
  build:
    name: Build and run UI tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.5.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build Showcase app
        run: yarn build:showcase
      - name: Install Playwright browsers
        run: npm --workspace=@furystack/shades-showcase-app e2e install --with-deps
      - name: execute tests
        run: npm --workspace=@furystack/shades-showcase-app e2e test
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: packages/shades-showcase-app/test-results
          name: Download-screenshots  